# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d1998ee560fdb758a7db5feb629eaf04b028baf6b5b27ecbf63b8a78f9d801165c26d640220ea8743edd4453e155c169f299bf1730ac9d2de194a7fb2d1f98f

test:
  secret_key_base: c07a486a3999f7004c31b39aa9516c87deddc0c6e564615b9158bed3f3365b6553fe3435465b3b1a3b6cbb9ccc244a683863cdbf793b63a144fe790cd25505e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
